const catalogParts = [
  { mpn: 'FT232RL-REEL', manufacturer: 'FTDI', description: 'USB to UART Bridge', category: 'Interface', package: 'SSOP-28', lifecycle: 'EOL', yteolYears: 0, stock: 0, unitPrice: null, trend: 'down', compliance: ['RoHS'], distributors: ['DigiKey', 'Mouser', 'Arrow'] },
  { mpn: 'ADP7142ARDZ-3.3', manufacturer: 'Analog Devices', description: 'Low Noise 3.3V LDO 200mA', category: 'Power', package: 'SOIC-8', lifecycle: 'NRND', yteolYears: 1, stock: 0, unitPrice: 3.85, trend: 'down', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey'] },
  { mpn: 'LM1117MPX-3.3', manufacturer: 'Texas Instruments', description: '3.3V LDO Regulator 800mA', category: 'Power', package: 'SOT-223', lifecycle: 'NRND', yteolYears: 2, stock: 45, unitPrice: 1.02, trend: 'down', compliance: ['RoHS'], distributors: ['DigiKey', 'Mouser'] },
  { mpn: 'SN65HVD230DR', manufacturer: 'Texas Instruments', description: 'CAN Bus Transceiver', category: 'Interface', package: 'SOIC-8', lifecycle: 'Active', yteolYears: 8, stock: 80, unitPrice: 2.09, trend: 'flat', compliance: ['RoHS', 'AEC-Q100'], distributors: ['DigiKey', 'Mouser', 'LCSC'] },
  { mpn: 'ESD7004MUTAG', manufacturer: 'onsemi', description: 'TVS Diode Array USB ESD', category: 'Protection', package: 'SOT-553', lifecycle: 'Active', yteolYears: 6, stock: 30, unitPrice: 0.19, trend: 'flat', compliance: ['RoHS'], distributors: ['DigiKey', 'Mouser'] },
  { mpn: 'STM32F407VGT6', manufacturer: 'STMicroelectronics', description: 'ARM Cortex-M4 MCU 168MHz 1MB', category: 'MCU', package: 'LQFP-100', lifecycle: 'Active', yteolYears: 12, stock: 8500, unitPrice: 6.88, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser', 'Arrow'] },
  { mpn: 'GRM155R71C104KA88D', manufacturer: 'Murata', description: '100nF 16V X7R 0402', category: 'Capacitor', package: '0402', lifecycle: 'Active', yteolYears: 15, stock: 250000, unitPrice: 0.0044, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser', 'LCSC'] },
  { mpn: 'RC0402FR-0710KL', manufacturer: 'Yageo', description: '10KΩ 1% 0402 Resistor', category: 'Resistor', package: '0402', lifecycle: 'Active', yteolYears: 18, stock: 500000, unitPrice: 0.0017, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser', 'LCSC'] },
  { mpn: 'W25Q128JVSIQ', manufacturer: 'Winbond', description: '128Mbit SPI Flash', category: 'Memory', package: 'SOIC-8', lifecycle: 'Active', yteolYears: 10, stock: 15000, unitPrice: 1.18, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser'] },
  { mpn: 'CSTCE16M0V53-R0', manufacturer: 'Murata', description: '16MHz Ceramic Resonator', category: 'Crystal', package: '0603', lifecycle: 'Active', yteolYears: 14, stock: 32000, unitPrice: 0.25, trend: 'up', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser'] },
  { mpn: 'BAT54S', manufacturer: 'Nexperia', description: 'Dual Schottky Diode', category: 'Diode', package: 'SOT-23', lifecycle: 'Active', yteolYears: 16, stock: 120000, unitPrice: 0.04, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser', 'LCSC'] },
  { mpn: 'TPS62160DSGR', manufacturer: 'Texas Instruments', description: '1A Step-Down Converter 3-17V', category: 'Power', package: 'WSON-8', lifecycle: 'Active', yteolYears: 11, stock: 7200, unitPrice: 1.76, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser'] },
  { mpn: 'AP2112K-3.3', manufacturer: 'Diodes Inc.', description: '600mA Low Dropout 3.3V LDO', category: 'LDO', package: 'SOT-23-5', lifecycle: 'Active', yteolYears: 8, stock: 84000, unitPrice: 0.18, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser', 'LCSC'], vinMin: 2.5, vinMax: 6, vout: 3.3, ioutMax: 0.6, noise: 0.055, tempMin: -40, tempMax: 85, price1k: 0.18 },
  { mpn: 'NCP1117ST33T3G', manufacturer: 'onsemi', description: '1A LDO 3.3V', category: 'LDO', package: 'SOT-223', lifecycle: 'Active', yteolYears: 7, stock: 67000, unitPrice: 0.41, trend: 'flat', compliance: ['AEC-Q100'], distributors: ['DigiKey', 'Mouser', 'LCSC'], vinMin: 4.75, vinMax: 18, vout: 3.3, ioutMax: 1.0, noise: 0.18, tempMin: -40, tempMax: 125, price1k: 0.41 },
  { mpn: 'TLV75533PDBVR', manufacturer: 'Texas Instruments', description: '500mA 3.3V LDO with PG', category: 'LDO', package: 'SOT-23-5', lifecycle: 'Active', yteolYears: 9, stock: 32000, unitPrice: 0.32, trend: 'flat', compliance: ['RoHS', 'REACH', 'AEC-Q100'], distributors: ['DigiKey', 'Arrow'], vinMin: 1.4, vinMax: 5.5, vout: 3.3, ioutMax: 0.5, noise: 0.03, tempMin: -40, tempMax: 125, price1k: 0.32 },
  { mpn: 'MIC5219-3.3YM5', manufacturer: 'Microchip', description: '500mA LDO 3.3V', category: 'LDO', package: 'SOT-23-5', lifecycle: 'Active', yteolYears: 9, stock: 18500, unitPrice: 0.62, trend: 'flat', compliance: ['RoHS', 'REACH'], distributors: ['DigiKey', 'Mouser'], vinMin: 2.5, vinMax: 12, vout: 3.3, ioutMax: 0.5, noise: 0.26, tempMin: -40, tempMax: 125, price1k: 0.62 }
];

const catalogByMpn = new Map(catalogParts.map((part) => [String(part.mpn).toUpperCase(), part]));

module.exports = {
  catalogParts,
  catalogByMpn,
};
